# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1st():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_1st(self):
    self.driver.get("https://www.google.ru/")
    self.driver.set_window_size(1449, 781)
    self.driver.find_element(By.NAME, "q").send_keys("bundyusoft")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".g:nth-child(2) .LC20lb").click()
    self.vars["win4313"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win4313"])
    self.driver.find_element(By.CSS_SELECTOR, ".btn--lg").click()
    assert self.driver.find_element(By.LINK_TEXT, "8 800 775-15-21").text == "8 800 775-15-21"
    assert self.driver.find_element(By.LINK_TEXT, "sales@byndyusoft.com").text == "sales@byndyusoft.com"
  
